### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "tess612@test.com",
  "password": "ndhtrangg612"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "tess@test.com",
  "password": "ndhtrangg612"
}

### Get the current signin user
GET http://localhost:3000/auth/whoami

### Signout
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=test@test.com

### Update a user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "password": "ndhtrangggg"
}

### Delete a user a given id
DELETE http://localhost:3000/auth/4

