POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZ0aGFuaC5hbjU3N0BnbWFpbC5jb20iLCJpYXQiOjE2ODEzMTE2NzMsImV4cCI6MTY4MTMxNzc5NX0.-Q2udW2cCTWryTsV9tDxbr7QSFem70h8zOgGVT-Ul8w

{
  "title": "Post test 2",
  "content": "test",
  "description": "test"
}

###
GET http://localhost:3000/post

###
GET http://localhost:3000/post/6436c7e0e9334fdbe846f47b

###
PUT http://localhost:3000/post/6435560d0e7814ad9c11fe70
Content-Type: application/json

{
  "title": "Post test 3",
  "content": "test",
  "description": "test"
}

###
DELETE http://localhost:3000/post/6435560d0e7814ad9c11fe70

###
GET http://localhost:3000/post/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZ0aGFuaC5hbjU3N0BnbWFpbC5jb20iLCJpYXQiOjE2ODEzMTIzODYsImV4cCI6MTY4MTMxODUwOH0.UkdCHd0y07_yADVff2grpItNCJcd1JsxHbUOvPh2PQQ
